AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'spec/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
   Enabled: False

Metrics/MethodLength:
  Max: 20
