default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ruby_clothing_store_development

test:
  <<: *default
  database: ruby_clothing_store_test
  
production:
  <<: *default
  database: ruby_clothing_store_production
  username: ruby_clothing_store
  password: <%= ENV['RUBY_CLOTHING_STORE_DATABASE_PASSWORD'] %>
